### ISSUE TITLE
Text preview

### ISSUE THREAD

**Issue by 5ock4** [copr/svinov2#6]
Špatně se zobrazuje text na konci preview článku.. chybí tři tečky..
![2](https://cloud.githubusercontent.com/assets/10260138/12007991/32d8d2f0-ac20-11e5-80f2-1db20a941d76.PNG)
 Checked in: chrome, IE
Affected: chrome, IE

**Comment by copr** [comment]
V Chromu už by to snad mohlo být. Tak zkontroluj chrom i iE. @5ock4
