### ISSUE TITLE
statistika

### ISSUE THREAD

**Issue by 5ock4** [copr/svinov2#8]
![statistika](https://cloud.githubusercontent.com/assets/10260138/12043326/8ca48bc4-ae84-11e5-9b32-a51e937e5f75.PNG)
chybi T

**Comment by copr** [comment]
Vyřešeno, ale není to moje starost. Mělo by to být na adminech.

**Comment by 5ock4** [comment]
aha jsem nevedel nebo zapomnel, ze admini muzou vytvaret sekce..
